---
abstract: 'RT-Extension-Assets Extension'
author:
  - 'Best Practical Solutions'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Assets
no_index:
  directory:
    - etc
    - html
    - inc
    - po
    - static
    - xt
  package:
    - HTML::Mason::Commands
    - RT::Transaction
    - RT::CustomField
    - RT::CustomFields
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.02'
x_module_install_rtx_version: '0.36'
x_requires_rt: 4.2.1
