---
abstract: 'RT Extension-Assets Extension'
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Assets
no_index:
  directory:
    - etc
    - html
    - inc
    - po
    - xt
  package:
    - HTML::Mason::Commands
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
